# Dependencies
markdown:         kramdown

# Permalinks
permalink:        pretty

# Setup
title:            Haven Kim
tagline:          'Junior Developer'

description:      'Spell book.</br>By Haven Kim.'
baseurl:          / #https://raacker.github.io/

author:
  name:           'Haven Kim'
  url:            https://

# Use Paginate
paginate:         3
paginate_path:    '/blog/page:num'
gems:             [jekyll-paginate]

# Custom vars
version:          1.1.0

github:
  repo:           https://github.com/raacker

LinkedIn:
  addr:           https://kr.linkedin.com/in/heongyeom-kim-633650113


# Atom Setting
atom:
  buildCommand:
    - jekyll
    - build
    - --option
    - --this
  buildEnv:
    JEKYLL_ENV: development
  postDirs:
    - _newsletters
  defaultPostDir: _drafts
